<a href="https://colab.research.google.com/github/nelaaulina/AI-Praktikum_G.231.20.0164/blob/main/AIPraktikum7_G_231_20_0164.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import files
filenya= files.upload()

Saving Iris.csv to Iris (1).csv


In [ ]:
import io
df = pd.read_csv(io.StringIO(filenya['Iris.csv'].decode('utf-8)')))
print(df)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

In [ ]:
df.loc[df["Species"]=="Iris-setosa","Species"]=0
df.loc[df["Species"]=="Iris-versicolor","Species"]=1
df.loc[df["Species"]=="Iris-virginica","Species"]=2
print(df.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0   1            5.1           3.5            1.4           0.2       0
1   2            4.9           3.0            1.4           0.2       0
2   3            4.7           3.2            1.3           0.2       0
3   4            4.6           3.1            1.5           0.2       0
4   5            5.0           3.6            1.4           0.2       0


In [ ]:
df=df.iloc[np.random.permutation(len(df))]
print(df.head())

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
89  90            5.5           2.5            4.0           1.3       1
61  62            5.9           3.0            4.2           1.5       1
52  53            6.9           3.1            4.9           1.5       1
37  38            4.9           3.1            1.5           0.1       0
66  67            5.6           3.0            4.5           1.5       1


In [ ]:
X=df.iloc[:,1:5].values
y=df.iloc[:,5].values

print("Shape of X",X.shape)
print("Shape of y",y.shape)
print("Examples of X\n",X[:3])
print("Examples of y\n",y[:3])

Shape of X (150, 4)
Shape of y (150,)
Examples of X
 [[5.5 2.5 4.  1.3]
 [5.9 3.  4.2 1.5]
 [6.9 3.1 4.9 1.5]]
Examples of y
 [1 1 1]


In [ ]:
X_normalized=normalize(X,axis=0)
print("Examples of X_normalised\n",X_normalized[:3])

Examples of X_normalised
 [[0.07609697 0.06617903 0.07870418 0.07476947]
 [0.08163129 0.07941484 0.08263939 0.08627246]
 [0.0954671  0.082062   0.09641262 0.08627246]]


In [ ]:
#Creating train,test and validation data
'''
80% -- train data
20% -- test data
'''
total_length=len(df)
train_length=int(0.8*total_length)
test_length=int(0.2*total_length)

X_train=X_normalized[:train_length]
X_test=X_normalized[train_length:]
y_train=y[:train_length]
y_test=y[train_length:]

print("Length of train set x:",X_train.shape[0],"y:",y_train.shape[0])
print("Length of test set x:",X_test.shape[0],"y:",y_test.shape[0])

Length of train set x: 120 y: 120
Length of test set x: 30 y: 30


In [ ]:
#Neural network module
from keras.models import Sequential
from keras.layers import Dense,Activation,Dropout
from keras.utils import np_utils

In [ ]:
#Change the label to one hot vector
'''
[0]--->[1 0 0]
[1]--->[0 1 0]
[2]--->[0 0 1]
'''
y_train=np_utils.to_categorical(y_train,num_classes=3)
y_test=np_utils.to_categorical(y_test,num_classes=3)
print("Shape of y_train",y_train.shape)
print("Shape of y_test",y_test.shape)

Shape of y_train (120, 3)
Shape of y_test (30, 3)


In [ ]:
model=Sequential()
model.add(Dense(1000,input_dim=4,activation='relu'))
model.add(Dense(500,activation='relu'))
model.add(Dense(300,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1000)              5000      
                                                                 
 dense_1 (Dense)             (None, 500)               500500    
                                                                 
 dense_2 (Dense)             (None, 300)               150300    
                                                                 
 dropout (Dropout)           (None, 300)               0         
                                                                 
 dense_3 (Dense)             (None, 3)                 903       
                                                                 
Total params: 656,703
Trainable params: 656,703
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),batch_size=20,epochs=10,verbose=1)

Epoch 1/10
6/6 [==============================] - 1s 45ms/step - loss: 1.0857 - accuracy: 0.4667 - val_loss: 1.0616 - val_accuracy: 0.6667
Epoch 2/10
6/6 [==============================] - 0s 12ms/step - loss: 1.0292 - accuracy: 0.6417 - val_loss: 0.9701 - val_accuracy: 0.6667
Epoch 3/10
6/6 [==============================] - 0s 12ms/step - loss: 0.9128 - accuracy: 0.6750 - val_loss: 0.8095 - val_accuracy: 0.6667
Epoch 4/10
6/6 [==============================] - 0s 10ms/step - loss: 0.7393 - accuracy: 0.7083 - val_loss: 0.6096 - val_accuracy: 0.6667
Epoch 5/10
6/6 [==============================] - 0s 10ms/step - loss: 0.5448 - accuracy: 0.7917 - val_loss: 0.4278 - val_accuracy: 0.7667
Epoch 6/10
6/6 [==============================] - 0s 11ms/step - loss: 0.3729 - accuracy: 0.9250 - val_loss: 0.3185 - val_accuracy: 0.9333
Epoch 7/10
6/6 [==============================] - 0s 10ms/step - loss: 0.2906 - accuracy: 0.9417 - val_loss: 0.2165 - val_accuracy: 0.9667
Epoch 8/10
6/6 [===========

In [ ]:
prediction=model.predict(X_test)
length=len(prediction)
y_label=np.argmax(y_test,axis=1)
predict_label=np.argmax(prediction,axis=1)

accuracy=np.sum(y_label==predict_label)/length * 100
print("Accuracy of the dataset",accuracy )

1/1 [==============================] - 0s 71ms/step
Accuracy of the dataset 96.66666666666667


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
predictions = np.argmax(model.predict(X_test), axis=1)
Y_test = np.argmax(y_test,axis=1)
print(confusion_matrix(Y_test,predictions))
print(classification_report(Y_test,predictions))

1/1 [==============================] - 0s 81ms/step
[[11  0  0]
 [ 0 10  0]
 [ 0  1  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.91      1.00      0.95        10
           2       1.00      0.89      0.94         9

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30

